name: Release Build

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Publish Windows
        run: dotnet publish Al-DiscordRP/Al-DiscordRP.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false

      - name: Publish macOS
        run: dotnet publish Al-DiscordRP/Al-DiscordRP.csproj -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false

      - name: Publish Linux
        run: dotnet publish Al-DiscordRP/Al-DiscordRP.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false

      - name: Zip Releases
        run: |
          Compress-Archive -Path "Al-DiscordRP/bin/Release/net9.0/win-x64/publish/*" -DestinationPath "AlRP-Windows.zip"
          Compress-Archive -Path "Al-DiscordRP/bin/Release/net9.0/osx-x64/publish/*" -DestinationPath "AlRP-macOS.zip"
          Compress-Archive -Path "Al-DiscordRP/bin/Release/net9.0/linux-x64/publish/*" -DestinationPath "AlRP-Linux.zip"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            AlRP-Windows.zip
            AlRP-macOS.zip
            AlRP-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}